from sqlalchemy.orm import sessionmaker
from db_create import *

engine = create_engine('sqlite:///testing.db', encoding='utf-8', echo=True)
Session = sessionmaker(bind=engine)
session = Session()

session.add(Users('aaa', 'ААА', 'ААААА','1234', 0))
session.add(Users('olesya', 'Олеся', 'Транина','1111',1))

session.add(Subjects('Математика'))
session.add(Subjects('Физика'))
session.add(Subjects('ОБЖ'))
session.add(Subjects('Химия'))

session.add(Tests(1, 'Арифметические операции 1'))
session.add(Tests(1, 'Арифметические операции 2'))
session.add(Tests(1, 'Решение уравнений'))
session.add(Tests(2, 'Законы Ньютона'))
session.add(Tests(3, 'Что делать при пожаре?'))

session.add(Questions(1, '2+2=?', 'ONE_ANSWER'))
session.add(Questions(1, '10-0=?', 'MANY_ANSWERS'))
session.add(Questions(1, '6/2=?', 'INPUT_ANSWER'))
session.add(Questions(1, '2*4=?', 'ONE_ANSWER'))
session.add(Questions(2, '22*4=?', 'ONE_ANSWER'))
session.add(Questions(2, '20/4=?', 'MANY_ANSWERS'))
session.add(Questions(2, '2 (<|>) 4', 'INPUT_ANSWER'))

session.add(AnswerChoices(1, '1'))
session.add(AnswerChoices(1, '2'))
session.add(AnswerChoices(1, '3'))
session.add(AnswerChoices(1, '4'))
session.add(AnswerChoices(2, '10'))
session.add(AnswerChoices(2, '>0'))
session.add(AnswerChoices(2, '<0'))
session.add(AnswerChoices(2, '1'))
session.add(AnswerChoices(3, '3'))
session.add(AnswerChoices(4, '7'))
session.add(AnswerChoices(4, '8'))

session.add(AnswerChoices(5, '8'))
session.add(AnswerChoices(5, '88'))
session.add(AnswerChoices(6, '5'))
session.add(AnswerChoices(6, '4'))
session.add(AnswerChoices(6, '>0'))
session.add(AnswerChoices(6, '2'))
session.add(AnswerChoices(7, '<'))

session.add(CorrectAnswers(1, 4))
session.add(CorrectAnswers(2, 5))
session.add(CorrectAnswers(2, 6))
session.add(CorrectAnswers(3, 9))
session.add(CorrectAnswers(4, 11))
session.add(CorrectAnswers(5, 13))
session.add(CorrectAnswers(6, 14))
session.add(CorrectAnswers(6, 16))
session.add(CorrectAnswers(7, 18))
session.commit()
